dist: xenial

language: node_js

node_js:
  - "8"

stages:
  - lint
  - deploy

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      script: make && make docker/run target=lint
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-aws-tardigrade-pcx
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [terraform-aws-tardigrade-pcx v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-aws-tardigrade-pcx/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: QSil68zsSOIX7s1ips1NacLbuFw2qX5907KUh8x5TRL9iGHlMPYA8U4sF8rXWgU4+2jYMI6LPcA2oHO9FYMLP/K6gyW9G5FYrpj9pMQj8ASAvsLAx5aLK0ryTOHw09F6GFOlysIoqQ6b6LQqyKe0e2W/9HaADMwBWSPczUUby6OdETkkf/Qg2BkuAxLaUrrCE30GVEsUoXP9ttR6eFcQ36uwcUT9F926Cq8tduzlM4hdC4XaODqq5Cs5fPkLrY8NqFOpGzNSz1QDdCZicvX+y4puluNIljcwPnxMvpG+I+La8BTHmtZzSwpKRHdbxWqMin0G22fZwCgPdq3B7jI0Vn/LC4Qha8Pj4+c8SENk5iZFKZwSBNiYrUOxG22rHV621d7WVpc4Iza6hFTFyMceEBLlJYLxkbeAwCPsNMTjTUYldv7xXj7D3Y0arQqnoBBDeksCkb+lQVHVDk/YT/QPe8fN4s6FpSuiyM3oy5LQgSZgsJtUviTyUaRl7nOsY3qy3kceacNEX3I8Ko/RBVd7nBY7X0YqjUnWZH8lBHiDDid1IYx2WyceWkXCpjxAydWapjMfRjghCZzqoyI1iQOsOG9+GtCG31ZyRhIv2S8VDp8Q9tq6O8d9/G4zoE9nYiCPO5fVo34bFdbR+dlW06ZmTDOEdnus2t+GevTPZ3Hn5wo=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-aws-tardigrade-pcx
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
